Rocky/Rocky/Models/AplicationType.cs
using System.ComponentModel.DataAnnotations;

namespace Rocky.Models
{
    public class AplicationType
    {
        [Key]
        public int Id { get; set; }

        [Required (ErrorMessage = "El nombre es obligatorio.")]
        public string Name { get; set; }
    }
}

Rocky/Rocky/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Rocky.Models
{
    public class Category
    {
        [Key] //Simboliza la llave foranea
        public int Id { get; set; }

        [Required]

        public string Name { get; set; }

        
        [DisplayName("Display Order")]

        [Required]

        [Range(1, int.MaxValue, ErrorMessage ="Display Order for category must be greater than 0 ")]
        public int DisplayOrder { get; set; }

    }
}

Rocky/Rocky/Models/ErrorViewModel.cs
using System;

namespace Rocky.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rocky/Rocky/Controllers/ApplicationTypeController.cs
 using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Rocky.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly AplicationDbContext _db;

        public ApplicationTypeController (AplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<AplicationType> objList = _db.AplicationType;
            return View(objList);
        }


        //GET - CREATE 
        public IActionResult Create()
        {
            return View();
        }

        //  POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create (AplicationType obj)
        {

            if (ModelState.IsValid)
            {


                _db.AplicationType.Add(obj);
                _db.SaveChanges();
            }else
            {
                IEnumerable<string> errors = ModelState.Values.SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage);
            }
            return RedirectToAction("Index");

        }

        //GET - EDIT 
        public IActionResult Edit (int? id)
        {
            if(id == null || id ==0)
            {
                return NotFound();
            }
            var obj = _db.AplicationType.Find(id);
            if(obj == null)
            {
                return NotFound(); 
            }
            return View(obj);
        }

        //POST - EDIT 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit (AplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _db.AplicationType.Update(obj); //Agregando el objeto de tipo ApplicationType
                _db.SaveChanges(); //Guardando Cambios
                return RedirectToAction("Index"); //Redireccionando al index
            }

            return View(obj);
        }

        //GET-DELETE
        public IActionResult Delete (int? id)
        {
            if(id == null || id ==0)
            {
                return NotFound();
            }
            var obj = _db.AplicationType.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        // POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeletePost(int? id)
        {
            var obj = _db.AplicationType.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            _db.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Rocky/Rocky/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata;
using Rocky.Data;
using Rocky.Models;
using System.Collections.Generic;

namespace Rocky.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AplicationDbContext _db;

        public CategoryController(AplicationDbContext db)
        {
            _db=db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objList = _db.Category; 
            return View(objList);
        }
        

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST- CREATE 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(obj); //Agrega el objeto de tipo Categoria
                _db.SaveChanges(); //Guarda los cambios
                return RedirectToAction("Index"); //Redirecciona al index
            }

            return View(obj);
        }

        // GET - EDIT 
        public IActionResult Edit (int? id)
        {
            if(id == null || id==0)
            {
                return NotFound();
            }
            var obj = _db.Category.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST- EDIT  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Update(obj); //Agrega el objeto de tipo Categoria
                _db.SaveChanges(); //Guarda los cambios
                return RedirectToAction("Index"); //Redirecciona al index
            }

            return View(obj);
        }

        //POST - Delete 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Category.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            
                _db.Remove(obj); //Borrar de la base de datos 
                _db.SaveChanges(); //Guarda los cambios
                return RedirectToAction("Index"); //Redirecciona al index
            

            
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id==0)
            {
                return NotFound();
            }
            var obj = _db.Category.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj); //RETORNA A LA VISTA CON EL MISMO NOMBRE DEL METODO , SI ES DIFF NO VA A LLEGAR
        }
    }


}

Rocky/Rocky/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rocky.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rocky/Rocky/Views/ApplicationType/Delete.cshtml
@model Rocky.Models.AplicationType;
<form method="post" asp-action="DeletePost">
    <!--Cuando se mande un post tiene que caer en ese metodod-->
    <input asp-for="Id" hidden /> <!--Asociando con aspFor el Id que se manda -->

    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">

            <h2 class="text-info pl-3"> Delete Application</h2>
        </div>

        <div class="row">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" disabled class="form-control" />

                </div>
            </div>
           
            <div class="form-group row">
                <div class="col">
                    <input type="submit" class="btn btn-danger w-100" value="Delete" />


                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success w-100">
                        <i class="fas fa-sign-out-alt"></i>
                        <i class="fa-solid fa-right-from-bracket"></i>
                    </a>

                </div>
            </div>
        </div>




    </div>
    <div class="col-4">
    </div>
    </div>
    </div>

</form>

<!-- Aca para validar desde el lado del servidor-->
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky/Rocky/Views/ApplicationType/Edit.cshtml
@model Rocky.Models.AplicationType;

<form method="post">
    <input asp-for="Id" hidden /> <!--Asociando con aspFor el Id que se manda -->

    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">

            <h2 class="text-info pl-3"> Edit Application Type</h2>
        </div>

        <div class="row">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
           
            <div class="form-group row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-100" value="Update" />


                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success w-100">
                        <i class="fas fa-sign-out-alt"></i>
                        <i class="fa-solid fa-right-from-bracket"></i>
                    </a>

                </div>
            </div>
        </div>




    </div>
    <div class="col-4">
    </div>
    </div>
    </div>

</form>

<!-- Aca para validar desde el lado del servidor-->
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky/Rocky/Views/ApplicationType/Index.cshtml
@model IEnumerable<AplicationType> 

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application List</h2>
        </div>
        <div class="col-6 text-right">
            <a  asp-action="Create" class="btn btn-primary"> Create New Application Type </a>
              
        </div>
    </div>

    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                         Name
                    </th>
                    
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model){
                    <tr>
                        <td width="50%">@obj.Name </td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="fa-sharp fa-regular fa-trash"></i>
                                </a>
                            </div>
                        </td>
                        <td></td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No application exists.</p>
    }
</div>

Rocky/Rocky/Views/ApplicationType/create.cshtml
@model Rocky.Models.AplicationType;

<form method="post" asp-action="Create">

    <div class="border p-3">
        <div class="form-group row">

            <h2 class="text-info pl-3"> Add Application Type</h2>
        </div>

        <div class="row">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label> 
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control"/> 
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            
            <div class="form-group row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-100"  value="Create"/> 


                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>BACK</a>

                </div>
            </div>
        </div>




    </div>
        <div class="col-4">


        </div>
    </div>
  </div>

</form>

@section Scripts{
  @{<partial name="_ValidationScriptsPartial" />}

}

Rocky/Rocky/Views/Category/Delete.cshtml
@model Rocky.Models.Category;

<form method="post" asp-action="DeletePost"> <!--Cuando se mande un post tiene que caer en ese metodod-->
    <input  asp-for="Id" hidden/> <!--Asociando con aspFor el Id que se manda -->

    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">

            <h2 class="text-info pl-3"> Delete Category</h2>
        </div>

        <div class="row">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" disabled class="form-control" />
               
                </div>
            </div>
            <div class="form-group row">

                <div class="col-4">
                    <label asp-for="DisplayOrder"></label>
                </div>
                <div class="col-8">
                    <input asp-for="DisplayOrder" disabled class="form-control" />
  
                </div>

            </div>
            <div class="form-group row">
                <div class="col">
                    <input type="submit" class="btn btn-danger w-100" value="Delete" />


                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>
                        <i class="fa-solid fa-right-from-bracket"></i> 
                    </a>

                </div>
            </div>
        </div>




    </div>
    <div class="col-4">
    </div>
    </div>
    </div>

</form>

<!-- Aca para validar desde el lado del servidor-->
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky/Rocky/Views/Category/Edit.cshtml
@model Rocky.Models.Category;

<form method="post">
    <input  asp-for="Id" hidden/> <!--Asociando con aspFor el Id que se manda -->

    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">

            <h2 class="text-info pl-3"> Edit Category</h2>
        </div>

        <div class="row">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">

                <div class="col-4">
                    <label asp-for="DisplayOrder"></label>
                </div>
                <div class="col-8">
                    <input asp-for="DisplayOrder" class="form-control" />
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-100" value="Update" />


                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>
                        <i class="fa-solid fa-right-from-bracket"></i> 
                    </a>

                </div>
            </div>
        </div>




    </div>
    <div class="col-4">
    </div>
    </div>
    </div>

</form>

<!-- Aca para validar desde el lado del servidor-->
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky/Rocky/Views/Category/Index.cshtml
@model IEnumerable<Category> 

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> &nbsp; Create New Category
            </a>
              
        </div>
    </div>

    <br /> <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Category Name
                    </th>
                    <th>
                        Display Order
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model){
                    <tr>
                        <td width="50%">@obj.Name </td>
                        <td width="30%">@obj.DisplayOrder</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Category" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fa-solid fa-pen-to-square"></i> 
                                </a>
                                <a asp-controller="Category" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="fa-sharp fa-regular fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No category exists.</p>
    }
</div>

Rocky/Rocky/Views/Category/create.cshtml
@model Rocky.Models.Category;

<form method="post" asp-action="Create">

    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">

            <h2 class="text-info pl-3"> Add Category</h2>
        </div>

        <div class="row">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label> 
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control"/> 
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">

                <div class="col-4">
                    <label asp-for="DisplayOrder"></label>
                </div>
                <div class="col-8">
                    <input asp-for="DisplayOrder" class="form-control" />
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-100"  value="Create"/> 


                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>
                        <i class="fa-solid fa-right-from-bracket"></i> BACK
                    </a>

                </div>
            </div>
        </div>




    </div>
        <div class="col-4">


        </div>
    </div>
  </div>

</form>

<!-- Aca para validar desde el lado del servidor-->
@section Scripts{  
  @{<partial name="_ValidationScriptsPartial" />}

}

Rocky/Rocky/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rocky/Rocky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocky</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontAwesome/css/all.css" /> 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rocky</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Rocky - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>